/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package introducaoui;

import java.awt.Color;
import static java.awt.Color.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author alunom
 */
public class Intro3 extends javax.swing.JFrame {
    int numero,numero2;
    Timer temporizador;
    int velocidade = 500;
    int chances = 5;
    
    int painelClicado = 0;
    
    public Intro3() {
        initComponents();
        temporizador = new Timer(velocidade, acaoJoao);
        lbchances.setText("Chances: "+chances);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgnivel = new javax.swing.ButtonGroup();
        painel1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        painel3 = new javax.swing.JPanel();
        lb3 = new javax.swing.JLabel();
        painel7 = new javax.swing.JPanel();
        lb7 = new javax.swing.JLabel();
        painel2 = new javax.swing.JPanel();
        lb2 = new javax.swing.JLabel();
        painel6 = new javax.swing.JPanel();
        lb6 = new javax.swing.JLabel();
        painel11 = new javax.swing.JPanel();
        lb11 = new javax.swing.JLabel();
        painel8 = new javax.swing.JPanel();
        lb8 = new javax.swing.JLabel();
        painel12 = new javax.swing.JPanel();
        lb12 = new javax.swing.JLabel();
        painel13 = new javax.swing.JPanel();
        lb13 = new javax.swing.JLabel();
        painel4 = new javax.swing.JPanel();
        lb4 = new javax.swing.JLabel();
        painel14 = new javax.swing.JPanel();
        lb14 = new javax.swing.JLabel();
        painel5 = new javax.swing.JPanel();
        lb5 = new javax.swing.JLabel();
        painel9 = new javax.swing.JPanel();
        lb9 = new javax.swing.JLabel();
        painel10 = new javax.swing.JPanel();
        lb10 = new javax.swing.JLabel();
        painel15 = new javax.swing.JPanel();
        lb15 = new javax.swing.JLabel();
        btcomecar = new javax.swing.JButton();
        btparar = new javax.swing.JButton();
        nivel1 = new javax.swing.JRadioButton();
        nivel2 = new javax.swing.JRadioButton();
        nivel3 = new javax.swing.JRadioButton();
        nivel4 = new javax.swing.JRadioButton();
        cbcor = new javax.swing.JComboBox();
        lbchances = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel1MouseClicked(evt);
            }
        });

        lb1.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel3MouseClicked(evt);
            }
        });

        lb3.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel3Layout = new javax.swing.GroupLayout(painel3);
        painel3.setLayout(painel3Layout);
        painel3Layout.setHorizontalGroup(
            painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb3, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel3Layout.setVerticalGroup(
            painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel7MouseClicked(evt);
            }
        });

        lb7.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel7Layout = new javax.swing.GroupLayout(painel7);
        painel7.setLayout(painel7Layout);
        painel7Layout.setHorizontalGroup(
            painel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb7, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel7Layout.setVerticalGroup(
            painel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb7, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel2MouseClicked(evt);
            }
        });

        lb2.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel2Layout = new javax.swing.GroupLayout(painel2);
        painel2.setLayout(painel2Layout);
        painel2Layout.setHorizontalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel2Layout.setVerticalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel6MouseClicked(evt);
            }
        });

        lb6.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel6Layout = new javax.swing.GroupLayout(painel6);
        painel6.setLayout(painel6Layout);
        painel6Layout.setHorizontalGroup(
            painel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb6, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel6Layout.setVerticalGroup(
            painel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb6, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel11MouseClicked(evt);
            }
        });

        lb11.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel11Layout = new javax.swing.GroupLayout(painel11);
        painel11.setLayout(painel11Layout);
        painel11Layout.setHorizontalGroup(
            painel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb11, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel11Layout.setVerticalGroup(
            painel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb11, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel8MouseClicked(evt);
            }
        });

        lb8.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel8Layout = new javax.swing.GroupLayout(painel8);
        painel8.setLayout(painel8Layout);
        painel8Layout.setHorizontalGroup(
            painel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb8, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel8Layout.setVerticalGroup(
            painel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb8, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel12MouseClicked(evt);
            }
        });

        lb12.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel12Layout = new javax.swing.GroupLayout(painel12);
        painel12.setLayout(painel12Layout);
        painel12Layout.setHorizontalGroup(
            painel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb12, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel12Layout.setVerticalGroup(
            painel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb12, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel13MouseClicked(evt);
            }
        });

        lb13.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel13Layout = new javax.swing.GroupLayout(painel13);
        painel13.setLayout(painel13Layout);
        painel13Layout.setHorizontalGroup(
            painel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb13, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel13Layout.setVerticalGroup(
            painel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb13, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel4MouseClicked(evt);
            }
        });

        lb4.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel4Layout = new javax.swing.GroupLayout(painel4);
        painel4.setLayout(painel4Layout);
        painel4Layout.setHorizontalGroup(
            painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb4, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel4Layout.setVerticalGroup(
            painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb4, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel14MouseClicked(evt);
            }
        });

        lb14.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel14Layout = new javax.swing.GroupLayout(painel14);
        painel14.setLayout(painel14Layout);
        painel14Layout.setHorizontalGroup(
            painel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb14, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel14Layout.setVerticalGroup(
            painel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb14, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel5MouseClicked(evt);
            }
        });

        lb5.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel5Layout = new javax.swing.GroupLayout(painel5);
        painel5.setLayout(painel5Layout);
        painel5Layout.setHorizontalGroup(
            painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb5, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel5Layout.setVerticalGroup(
            painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb5, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel9MouseClicked(evt);
            }
        });

        lb9.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel9Layout = new javax.swing.GroupLayout(painel9);
        painel9.setLayout(painel9Layout);
        painel9Layout.setHorizontalGroup(
            painel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb9, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel9Layout.setVerticalGroup(
            painel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb9, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel10MouseClicked(evt);
            }
        });

        lb10.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel10Layout = new javax.swing.GroupLayout(painel10);
        painel10.setLayout(painel10Layout);
        painel10Layout.setHorizontalGroup(
            painel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb10, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel10Layout.setVerticalGroup(
            painel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb10, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        painel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel15MouseClicked(evt);
            }
        });

        lb15.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        lb15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painel15Layout = new javax.swing.GroupLayout(painel15);
        painel15.setLayout(painel15Layout);
        painel15Layout.setHorizontalGroup(
            painel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb15, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        painel15Layout.setVerticalGroup(
            painel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb15, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        btcomecar.setText("Começar");
        btcomecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcomecarActionPerformed(evt);
            }
        });

        btparar.setText("Parar");
        btparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpararActionPerformed(evt);
            }
        });

        btgnivel.add(nivel1);
        nivel1.setText("Facil");
        nivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivel1ActionPerformed(evt);
            }
        });

        btgnivel.add(nivel2);
        nivel2.setText("Medio");
        nivel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivel2ActionPerformed(evt);
            }
        });

        btgnivel.add(nivel3);
        nivel3.setText("Dificil");
        nivel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivel3ActionPerformed(evt);
            }
        });

        btgnivel.add(nivel4);
        nivel4.setText("Ultra");
        nivel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivel4ActionPerformed(evt);
            }
        });

        cbcor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Preto", "Azul", "Verde", "Vermelho" }));

        lbchances.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbchances.setText("Chances: ");

        jButton1.setText("Zerar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem1.setText("Começar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btcomecar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btparar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(cbcor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbchances))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(painel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(painel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(painel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(198, 198, 198)
                            .addComponent(painel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(painel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(painel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nivel1)
                    .addComponent(nivel2)
                    .addComponent(nivel3)
                    .addComponent(nivel4))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nivel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nivel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nivel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nivel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(painel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(painel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(painel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(painel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(painel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbcor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btcomecar)
                        .addComponent(btparar)
                        .addComponent(lbchances)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcomecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcomecarActionPerformed
        comecarJogo();
    }//GEN-LAST:event_btcomecarActionPerformed

    private void btpararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpararActionPerformed
        temporizador.stop();
        btcomecar.setEnabled(true);
        btparar.setEnabled(false);
    }//GEN-LAST:event_btpararActionPerformed

    private void nivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivel1ActionPerformed
        velocidade = 500;
     
        
    }//GEN-LAST:event_nivel1ActionPerformed

    private void nivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivel2ActionPerformed
        velocidade = 250;
        
    }//GEN-LAST:event_nivel2ActionPerformed

    private void nivel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivel3ActionPerformed
        velocidade = 100;
        
    }//GEN-LAST:event_nivel3ActionPerformed

    private void nivel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivel4ActionPerformed
        velocidade = 1;
       
    }//GEN-LAST:event_nivel4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(temporizador.isRunning())
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            btparar.setEnabled(false);
        }else
        {
        temporizador.start();
        btcomecar.setEnabled(false);
        btparar.setEnabled(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void painel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel1MouseClicked
        if(numero == 1)
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
        }else
            {
                lb1.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel1MouseClicked

    private void painel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel2MouseClicked
       if(numero == 2)
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
        }else
            {
                lb2.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel2MouseClicked

    private void painel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel3MouseClicked
        if(numero == 3)
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
        }else
            {
                lb3.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel3MouseClicked

    private void painel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel4MouseClicked
      if(numero == 4)
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
        }else
            {
                lb4.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel4MouseClicked

    private void painel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel5MouseClicked
        if(numero == 5)
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
        }else
            {
                lb5.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel5MouseClicked

    private void painel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel6MouseClicked
        if(numero == 6)
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
        }else
            {
                lb6.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel6MouseClicked

    private void painel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel7MouseClicked
       if(numero == 7)
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
        }else
            {
                lb7.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel7MouseClicked

    private void painel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel8MouseClicked
        if(numero == 8)
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
        }else
            {
                lb8.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel8MouseClicked

    private void painel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel9MouseClicked
        if(numero == 9)
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
        }else
            {
                lb9.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel9MouseClicked

    private void painel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel10MouseClicked
        if(numero == 10)
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
        }else
            {
                lb10.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel10MouseClicked

    private void painel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel11MouseClicked
        if(numero == 11)
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
        }else
            {
                lb11.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel11MouseClicked

    private void painel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel12MouseClicked
        if(numero == 12)
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
        }else
            {
                lb12.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel12MouseClicked

    private void painel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel13MouseClicked
        if(numero == 13)
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
        }else
            {
                lb13.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel13MouseClicked

    private void painel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel14MouseClicked
        if(numero == 14)
        {
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
            temporizador.stop();
            btcomecar.setEnabled(true);
        }else
            {
                lb14.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel14MouseClicked

    private void painel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel15MouseClicked
        if(numero == 15)
        {
            temporizador.stop();
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANHOU");
        }else
            {
                lb15.setText("X");
                chances--;
            }
    }//GEN-LAST:event_painel15MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        chances = 5;
        lbchances.setText("Chances: "+chances);
        btparar.setEnabled(false);
        btcomecar.setEnabled(true);
        temporizador.stop();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void comecarJogo()
    {
        temporizador.start();
        btcomecar.setEnabled(false);
    }
    
    ActionListener acaoJoao = new ActionListener()
    {
        @Override
        public void actionPerformed(ActionEvent e) 
        {
        if(chances <= 0)
        {
            temporizador.stop();
            btparar.setEnabled(false);
            btcomecar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "Voce Perdeu");
            
        }else{
        temporizador.setDelay(velocidade);
        numero = (int) Math.ceil(Math.random()*15);
        lbchances.setText("Chances: "+chances);
        
            painel1.setBackground(white);
            painel2.setBackground(white);
            painel3.setBackground(white);
            painel4.setBackground(white);
            painel5.setBackground(white);
            painel6.setBackground(white);
            painel7.setBackground(white);
            painel8.setBackground(white);
            painel9.setBackground(white);
            painel10.setBackground(white);
            painel11.setBackground(white);
            painel12.setBackground(white);
            painel13.setBackground(white);
            painel14.setBackground(white);
            painel15.setBackground(white);
            
            lb1.setText("");
            lb2.setText("");
            lb3.setText("");
            lb4.setText("");
            lb5.setText("");
            lb6.setText("");
            lb7.setText("");
            lb8.setText("");
            lb9.setText("");
            lb10.setText("");
            lb11.setText("");
            lb12.setText("");
            lb13.setText("");
            lb14.setText("");
            lb15.setText("");
            
            
         switch(numero)
         {
             case 1:  painel1.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
             case 2:  painel2.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
             case 3:  painel3.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
             case 4:  painel4.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
             case 5:  painel5.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
             case 6:  painel6.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
             case 7:  painel7.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
             case 8:  painel8.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
             case 9:  painel9.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
             case 10: painel10.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
             case 11: painel11.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
             case 12: painel12.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
             case 13: painel13.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
             case 14: painel14.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
             case 15: painel15.setBackground(retornaCor(cbcor.getSelectedIndex())); 
                      break;
                 
         }
         }
        
        }
        
        public Color retornaCor(int posicao)
        {
            switch(posicao)
            {
                case 0: return Color.black;
                case 1: return Color.blue;
                case 2: return Color.green;
                case 3: return Color.red;
            }
            return null;
        }
        
    };
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intro3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intro3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intro3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intro3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intro3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcomecar;
    private javax.swing.ButtonGroup btgnivel;
    private javax.swing.JButton btparar;
    private javax.swing.JComboBox cbcor;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb10;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb12;
    private javax.swing.JLabel lb13;
    private javax.swing.JLabel lb14;
    private javax.swing.JLabel lb15;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel lb9;
    private javax.swing.JLabel lbchances;
    private javax.swing.JRadioButton nivel1;
    private javax.swing.JRadioButton nivel2;
    private javax.swing.JRadioButton nivel3;
    private javax.swing.JRadioButton nivel4;
    private javax.swing.JPanel painel1;
    private javax.swing.JPanel painel10;
    private javax.swing.JPanel painel11;
    private javax.swing.JPanel painel12;
    private javax.swing.JPanel painel13;
    private javax.swing.JPanel painel14;
    private javax.swing.JPanel painel15;
    private javax.swing.JPanel painel2;
    private javax.swing.JPanel painel3;
    private javax.swing.JPanel painel4;
    private javax.swing.JPanel painel5;
    private javax.swing.JPanel painel6;
    private javax.swing.JPanel painel7;
    private javax.swing.JPanel painel8;
    private javax.swing.JPanel painel9;
    // End of variables declaration//GEN-END:variables
}
